# This file is generated by SensePlover render
# Please do not edit this file. Use SensePlover render to regenerate
# Generate at git ref: 6c85624d0e2f578913b6b1981335e68b3274f0f3


if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
# using Clang
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
# using GCC
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
# using Intel C++
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
# using Visual Studio C++
    ADD_DEFINITIONS( /wd"4819" )
    ADD_DEFINITIONS( /wd"4251" )
    ADD_DEFINITIONS( /wd"4009" )
    ADD_DEFINITIONS( /wd"4003" )
    ADD_DEFINITIONS( /wd"4996" )
    ADD_DEFINITIONS( /wd"4800" )
    ADD_DEFINITIONS( /wd"4102" )
    ADD_DEFINITIONS( /wd"4309" )
    ADD_DEFINITIONS( /wd"4373" )
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GHS")
    ADD_DEFINITIONS( --diag_suppress=82 )
    ADD_DEFINITIONS( --diag_suppress=111 )
    ADD_DEFINITIONS( --diag_suppress=611 )
endif()
